[package]
name = "me"
version = "0.4.4"
edition = "2021"

[dependencies]
rocket ={version = "0.5.0"}
maud = {version = "0.26"}
charming = "0.4.0"
static_hero_icons = "0.3.0"
include_directory = "0.1.1"

[profile.dev]
opt-level = 0
